/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import EmployeeManagement.*;
import BusManagement.*;
import LogManagement.DutyLog;
import RegistryManagement.Registry;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

/**
 *
 * @author Sian Paul Lasaga
 */
public class CashierMainFrame extends javax.swing.JFrame {

    private List<String> logs = new ArrayList<>();
    private BusCompany busCompany = BusCompany.getInstance();
    private SimpleDateFormat sdf = new SimpleDateFormat("MMMM dd,yyyy");
    private ScheduleDetailsFrame schedFrame = new ScheduleDetailsFrame();
    private ManagePassengerFrame manageFrame = new ManagePassengerFrame();
    public Cashier cashier = null;
    private DutyLog dutyLog = DutyLog.getInstance();

    /**
     * Creates new form CashierMainFrame
     */
    public CashierMainFrame() {
        initComponents();
        dutyLog.setEmployee(cashier);
        dutyLog.setTimeIn(new Date());
//        cashierLabel.setText(cashier.getLastName() + ", " + cashier.getFirstName() + " " + cashier.getMiddleName());
        dateLabel.setText(sdf.format(dutyLog.getTimeIn()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cashierLabel = new javax.swing.JLabel();
        dateLabel = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        bookButton = new javax.swing.JButton();
        manageButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        cashierLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        cashierLabel.setText("Cashier name here");

        dateLabel.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        dateLabel.setText("Date");

        logOutButton.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        logOutButton.setText("Log out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        bookButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bookButton.setText("Book a Passenger");
        bookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookButtonActionPerformed(evt);
            }
        });

        manageButton.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        manageButton.setText("Manage Passenger Trips");
        manageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cashierLabel)
                .addGap(28, 28, 28)
                .addComponent(logOutButton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(manageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 389, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cashierLabel)
                    .addComponent(dateLabel)
                    .addComponent(logOutButton))
                .addGap(59, 59, 59)
                .addComponent(bookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(manageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void loadData(Cashier cashier) {
        this.cashier = cashier;
    }

    private void bookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookButtonActionPerformed
        // TODO add your handling code here:
        schedFrame.loadCashier(cashier);
        schedFrame.show();
    }//GEN-LAST:event_bookButtonActionPerformed

    private void manageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageButtonActionPerformed
        // TODO add your handling code here:
        manageFrame.loadCashier(cashier);
        manageFrame.show();
    }//GEN-LAST:event_manageButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        Registry registry=Registry.getInstance();
        dutyLog.setTimeOut(new Date());
        registry.addDutyLog(dutyLog);
        dutyLog.resetInstance();
        this.dispose();
        LoginFrame loginFrame = new LoginFrame();
        loginFrame.show();
    }//GEN-LAST:event_logOutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CashierMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CashierMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bookButton;
    private javax.swing.JLabel cashierLabel;
    private javax.swing.JLabel dateLabel;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton manageButton;
    // End of variables declaration//GEN-END:variables
}
