/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import BusManagement.*;
import CommandPatternClasses.Invoker;
import CommandPatternClasses.RemoveBusCommand;
import LogManagement.*;
import RegistryManagement.*;
import java.awt.event.WindowEvent;
import java.awt.event.WindowFocusListener;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author windows
 */
public class ManageBussesFrame extends javax.swing.JFrame implements WindowFocusListener {

    private Invoker invoker = new Invoker();
    private String busNumber;
    private Bus bus;
    private boolean hasSelected = false;
    private int selectedRow = 0;
    private BusCompany busCompany = BusCompany.getInstance();
    private SearchEngine searchEngine = new SearchEngine();
    private DutyLog dutyLog = DutyLog.getInstance();
    private Registry registry = Registry.getInstance();
    private DefaultTableModel busTableModel = new DefaultTableModel(
            new Object[]{"Bus Type", "Bus #", "Plate #", "Capacity", "Availability"}, 0);

    /**
     * Creates new form ManageBussesFrame
     */
    public ManageBussesFrame() {
        initComponents();
        setLocationRelativeTo(null);
        addWindowFocusListener(this);

        busTable.setModel(busTableModel);
        busTable.getTableHeader().setReorderingAllowed(false);
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        busTable.getTableHeader().setDefaultRenderer(centerRenderer);
        busTable.setRowSelectionAllowed(true);
        busTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        busTable.setEnabled(true);
        busTable.setSelectionBackground(java.awt.Color.GRAY);
        for (int c = 0; c < busTable.getColumnCount(); c++) {
            Class<?> col_class = busTable.getColumnClass(c);
            busTable.setDefaultEditor(col_class, null);        // remove editor
        }
        busTable.getTableHeader().setResizingAllowed(false);
        busTable.setShowGrid(true);

        updateTableModel();
        disableUnavailableFiltersCheckBox();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        busDataPanel = new javax.swing.JPanel();
        addBusButton = new javax.swing.JButton();
        editBusButton = new javax.swing.JButton();
        mainMenuButton = new javax.swing.JButton();
        logOutButton = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();
        removeBusButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        busTable = new javax.swing.JTable();
        filtersPanel = new javax.swing.JPanel();
        bussesWithUnavailableStatusCheckBox = new javax.swing.JCheckBox();
        withNoDriverAssignedCheckBox = new javax.swing.JCheckBox();
        withNoConductorAssignedCheckBox = new javax.swing.JCheckBox();
        withMechanicalIssuesCheckBox = new javax.swing.JCheckBox();
        allBussesButton = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        busDataPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Select Row to Edit/Remove Data", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));

        addBusButton.setText("Add Bus");
        addBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBusButtonActionPerformed(evt);
            }
        });

        editBusButton.setText("Edit Bus / Assign Crew");
        editBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBusButtonActionPerformed(evt);
            }
        });

        mainMenuButton.setText("Main Menu");
        mainMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainMenuButtonActionPerformed(evt);
            }
        });

        logOutButton.setText("Log Out");
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        removeBusButton.setText("Remove Bus");
        removeBusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeBusButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout busDataPanelLayout = new javax.swing.GroupLayout(busDataPanel);
        busDataPanel.setLayout(busDataPanelLayout);
        busDataPanelLayout.setHorizontalGroup(
            busDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(busDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addBusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainMenuButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logOutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(removeBusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        busDataPanelLayout.setVerticalGroup(
            busDataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(busDataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(editBusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(removeBusButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(mainMenuButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(logOutButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(exitButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        busTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        busTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                busTableMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(busTable);

        filtersPanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Filters", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        bussesWithUnavailableStatusCheckBox.setText("Busses w/ Unavailable Status");
        bussesWithUnavailableStatusCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bussesWithUnavailableStatusCheckBoxActionPerformed(evt);
            }
        });

        withNoDriverAssignedCheckBox.setText("w/ No Driver Assigned");
        withNoDriverAssignedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withNoDriverAssignedCheckBoxActionPerformed(evt);
            }
        });

        withNoConductorAssignedCheckBox.setText("w/ No Conductor Assigned");
        withNoConductorAssignedCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withNoConductorAssignedCheckBoxActionPerformed(evt);
            }
        });

        withMechanicalIssuesCheckBox.setText("w/ Mechanical Issues");
        withMechanicalIssuesCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                withMechanicalIssuesCheckBoxActionPerformed(evt);
            }
        });

        allBussesButton.setText("All Busses");
        allBussesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allBussesButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout filtersPanelLayout = new javax.swing.GroupLayout(filtersPanel);
        filtersPanel.setLayout(filtersPanelLayout);
        filtersPanelLayout.setHorizontalGroup(
            filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bussesWithUnavailableStatusCheckBox, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(withNoDriverAssignedCheckBox)
                    .addComponent(withNoConductorAssignedCheckBox)
                    .addComponent(withMechanicalIssuesCheckBox)
                    .addComponent(allBussesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        filtersPanelLayout.setVerticalGroup(
            filtersPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(filtersPanelLayout.createSequentialGroup()
                .addComponent(allBussesButton)
                .addGap(2, 2, 2)
                .addComponent(bussesWithUnavailableStatusCheckBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withNoDriverAssignedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withNoConductorAssignedCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(withMechanicalIssuesCheckBox, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(busDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filtersPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(busDataPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(filtersPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeTableRows() {
        while (busTable.getRowCount() > 0) {
            busTableModel.removeRow(0);
        }
    }

    private void updateTableModel() {
        removeTableRows();
        for (Bus bus : busCompany.getBusses()) {
            String busType = bus.getBusType() == BusType.ORDINARY ? "Ordinary" : "Air-conditioned";
            String available = bus.isAvailable() ? "Available" : "Unavailable";
            busTableModel.addRow(
                    new Object[]{busType, bus.getBusNumber(), bus.getPlateNumber(), bus.getCapacity(), available});
        }
    }

    private void removeBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeBusButtonActionPerformed
        if (hasSelected) {
            invoker.setCommand(new RemoveBusCommand(bus));
            invoker.executeCommand();
            updateTableModel();
        } else {
            JOptionPane.showMessageDialog(
                    null, "Select a row on the table before pressing remove button!", "No row selected", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_removeBusButtonActionPerformed

    private void addBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBusButtonActionPerformed
        BusRegistrationFrame busRegistrationFrame = new BusRegistrationFrame();
        busRegistrationFrame.show();
    }//GEN-LAST:event_addBusButtonActionPerformed

    private void mainMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainMenuButtonActionPerformed
        this.hide();
        ManagerMainMenu managerMainMenu = new ManagerMainMenu();
        managerMainMenu.show();
    }//GEN-LAST:event_mainMenuButtonActionPerformed

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed
        LoginFrame loginFrame = new LoginFrame();
        dutyLog.setTimeOut(new Date());
        registry.addDutyLog(dutyLog);
        dutyLog.resetInstance();
        this.dispose();
        loginFrame.show();
    }//GEN-LAST:event_logOutButtonActionPerformed

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dutyLog.setTimeOut(new Date());
        registry.addDutyLog(dutyLog);
        dutyLog.resetInstance();
        this.dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void editBusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBusButtonActionPerformed
        if (hasSelected) {
            BusRegistrationFrame busRegistrationFrame = new BusRegistrationFrame();
            busRegistrationFrame.load(bus);
            busRegistrationFrame.show();
        } else {
            JOptionPane.showMessageDialog(
                    null, "Select a row on the table before pressing view/edit button!", "No Row Selected", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_editBusButtonActionPerformed

    private void busTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_busTableMousePressed
        if (hasSelected && selectedRow == busTable.getSelectedRow()) {
            busTable.clearSelection();
            hasSelected = false;
            return;
        }

        selectedRow = busTable.getSelectedRow();
        hasSelected = true;

        busNumber = (String) busTable.getValueAt(selectedRow, 1);
        bus = searchEngine.searchBusByBusNo(busNumber);
    }//GEN-LAST:event_busTableMousePressed

    private void bussesWithUnavailableStatusCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bussesWithUnavailableStatusCheckBoxActionPerformed
        if (bussesWithUnavailableStatusCheckBox.isSelected()) {
            enableUnavailableFiltersCheckBox();
            checkUnavailableFilterCheckBoxes();
        } else {
            disableUnavailableFiltersCheckBox();
            checkUnavailableFilterCheckBoxes();
        }
        hasSelected=false;
    }//GEN-LAST:event_bussesWithUnavailableStatusCheckBoxActionPerformed

    private void disableUnavailableFiltersCheckBox() {
        withMechanicalIssuesCheckBox.setSelected(false);
        withNoConductorAssignedCheckBox.setSelected(false);
        withNoDriverAssignedCheckBox.setSelected(false);
        withMechanicalIssuesCheckBox.setEnabled(false);
        withNoDriverAssignedCheckBox.setEnabled(false);
        withNoConductorAssignedCheckBox.setEnabled(false);
    }

    private void enableUnavailableFiltersCheckBox() {
        withMechanicalIssuesCheckBox.setEnabled(true);
        withNoDriverAssignedCheckBox.setEnabled(true);
        withNoConductorAssignedCheckBox.setEnabled(true);
    }

    private void allBussesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allBussesButtonActionPerformed
        updateTableModel();
        disableUnavailableFiltersCheckBox();
        bussesWithUnavailableStatusCheckBox.setSelected(false);
        hasSelected=false;
    }//GEN-LAST:event_allBussesButtonActionPerformed

    private void checkUnavailableFilterCheckBoxes() {
        List<Bus> busses = new ArrayList<>();
        String available = "";
        if (bussesWithUnavailableStatusCheckBox.isSelected()) {
            for (Bus bus1 : busCompany.getBusses()) {
                if (!bus1.isAvailable()) {
                    busses.add(bus1);
                }
            }
            if (withNoDriverAssignedCheckBox.isSelected()) {
                int oldSize = busses.size();
                List<Bus> bussesToBeRemoved= new ArrayList<>();
                for (Bus bus1 : busses) {
                    if (bus1.getDriver() != null) {
                        bussesToBeRemoved.add(bus1);
                    }
                }
                busses.removeAll(bussesToBeRemoved);
                if (oldSize != busses.size()) {
                    available = "No Driver";
                }
            }
            if (withNoConductorAssignedCheckBox.isSelected()) {
                int oldSize = busses.size();
                List<Bus> bussesToBeRemoved= new ArrayList<>();
                for (Bus bus1 : busses) {
                    if (bus1.getConductor() != null) {
                        bussesToBeRemoved.add(bus1);
                    }
                }
                busses.removeAll(bussesToBeRemoved);
                if (oldSize != busses.size()) {
                    available = available + " & No Conductor";
                }
            }
            if (withMechanicalIssuesCheckBox.isSelected()) {
                int oldSize = busses.size();
                List<Bus> bussesToBeRemoved= new ArrayList<>();
                busses.removeAll(bussesToBeRemoved);
                if (oldSize != busses.size()) {
                    available = available + " & To Be Repaired";
                }
            }

            if (available.isEmpty()) {
                available = "Unavailable";
            }
        } else {
            for (Bus bus1 : busCompany.getBusses()) {
                if (bus1.isAvailable()) {
                    busses.add(bus1);
                }
            }
        }

        removeTableRows();
        if (!busses.isEmpty()) {
            for (Bus bus1 : busses) {
                String busType = bus1.getBusType() == BusType.ORDINARY ? "Ordinary" : "Air-conditioned";
                busTableModel.addRow(
                        new Object[]{busType, bus1.getBusNumber(), bus1.getPlateNumber(),
                            bus1.getCapacity(), available.isEmpty() ? "Available" : available});
            }
        }

    }

    private void withNoDriverAssignedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withNoDriverAssignedCheckBoxActionPerformed
        checkUnavailableFilterCheckBoxes();
        hasSelected=false;
    }//GEN-LAST:event_withNoDriverAssignedCheckBoxActionPerformed

    private void withNoConductorAssignedCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withNoConductorAssignedCheckBoxActionPerformed
        checkUnavailableFilterCheckBoxes();
        hasSelected=false;
    }//GEN-LAST:event_withNoConductorAssignedCheckBoxActionPerformed

    private void withMechanicalIssuesCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_withMechanicalIssuesCheckBoxActionPerformed
        hasSelected=false;
    }//GEN-LAST:event_withMechanicalIssuesCheckBoxActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageBussesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageBussesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageBussesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageBussesFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageBussesFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBusButton;
    private javax.swing.JButton allBussesButton;
    private javax.swing.JPanel busDataPanel;
    private javax.swing.JTable busTable;
    private javax.swing.JCheckBox bussesWithUnavailableStatusCheckBox;
    private javax.swing.JButton editBusButton;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel filtersPanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton logOutButton;
    private javax.swing.JButton mainMenuButton;
    private javax.swing.JButton removeBusButton;
    private javax.swing.JCheckBox withMechanicalIssuesCheckBox;
    private javax.swing.JCheckBox withNoConductorAssignedCheckBox;
    private javax.swing.JCheckBox withNoDriverAssignedCheckBox;
    // End of variables declaration//GEN-END:variables

    @Override
    public void windowGainedFocus(WindowEvent e) {
        if (!bussesWithUnavailableStatusCheckBox.isSelected()) {
            updateTableModel();
        } else {
            checkUnavailableFilterCheckBoxes();
        }
    }

    @Override
    public void windowLostFocus(WindowEvent e) {
        hasSelected = false;
    }
}
